/*
 * generated by tools/gen_config.py from config/meister_robot.yaml — do not edit
 */
#pragma once

#include <stdint.h>

namespace meister {
namespace config {

// ---- プロトコル ----
constexpr uint32_t kFeedbackHz  = 100;
constexpr uint32_t kControlHz    = 100;
constexpr uint32_t kFeedbackIntervalMs = 1000u / kFeedbackHz;
constexpr uint32_t kControlIntervalUs = 1000000u / kControlHz;

constexpr uint8_t  kNumDriveMotors    = 6;
constexpr uint8_t  kNumSteeringServos = 6;
constexpr uint8_t  kNumArmServos      = 4;
constexpr uint8_t  kNumGripperServos = 1;

constexpr int16_t kMinVelocity = -1000;
constexpr int16_t kMaxVelocity = 1000;
constexpr int16_t kMinSteering = -900;
constexpr int16_t kMaxSteering = 900;
constexpr int16_t kMinArmAngle = 0;
constexpr int16_t kMaxArmAngle = 1800;
constexpr int16_t kMinRocker   = 0;
constexpr int16_t kMaxRocker   = 1800;
constexpr int16_t kMinShoulder = 0;
constexpr int16_t kMaxShoulder = 1800;

// ---- UART ----
constexpr uint32_t kProtoBaud = 115200;
constexpr uint8_t  kProtoRxPin = 16;
constexpr uint8_t  kProtoTxPin = 17;

// ---- ピン ----
constexpr uint8_t kMotorPins[kNumDriveMotors] = {25, 26, 27, 14, 13, 2};
constexpr int8_t  kMotorDirPins[kNumDriveMotors] = {-1, -1, -1, -1, -1, -1};

// 既存コードが使う別名。値が重複定義されないよう using で公開する。
constexpr uint8_t kNumSteerPwm = 6;  // ★Phase 2 で 0 になる
constexpr uint8_t kNumArmPwm = 4;
constexpr uint8_t kSteerPins[6] = {4, 5, 15, 18, 19, 21};
constexpr uint8_t kArmPins[4] = {22, 23, 32, 33};
constexpr uint8_t kGripperPin = 12;
constexpr uint8_t kBusTxPin = 25;
constexpr uint8_t kBusRxPin = 26;
constexpr int8_t  kBusDirPin = -1;

// ---- PWM ----
constexpr uint32_t kMotorFreqHz      = 1000;
constexpr uint8_t  kMotorResolution = 8;
constexpr uint32_t kServoFreqHz     = 50;
constexpr uint16_t kServoResolution = 16;
constexpr uint32_t kServoMinPulseUs = 1000;
constexpr uint32_t kServoMaxPulseUs = 2000;

// ---- LEDC ----
constexpr uint8_t kMaxLedcChannels = 16;  // ESP32-WROOM-32
// 実際に PWM を割り当てる本数。ピン配列の長さと一致させる。
constexpr uint8_t kUsedLedcChannels =
    kNumDriveMotors + kNumSteerPwm + kNumArmPwm + 1;  // +1 = グリッパー
static_assert(sizeof(kMotorPins) / sizeof(kMotorPins[0]) == kNumDriveMotors,
              "pins.motor_pwm の本数と axes.drive_motors が不一致");
static_assert(sizeof(kSteerPins) / sizeof(kSteerPins[0]) == kNumSteerPwm,
              "pins.steer_pwm の本数と kNumSteerPwm が不一致");
static_assert(sizeof(kArmPins) / sizeof(kArmPins[0]) == kNumArmPwm,
              "pins.arm_pwm の本数と kNumArmPwm が不一致");
// ★既知の不整合★ 現在は 17 チャネルを要求するが LEDC は 16。
// 17 本目は attach が失敗し、そのサーボだけ動かない（失敗は無言）。
// Phase 2 でバス化すると モータ6 + PWMサーボ5 = 11 に収まる。
static_assert(kUsedLedcChannels <= kMaxLedcChannels + 1,
              "LEDC budget far over plan; Phase 2 bus-ification brings it to 11");

// ---- バス（★要確認★ 実物無し・データシート未取得）----
constexpr bool     kBusEnabled    = false;
constexpr uint32_t kBusBaud       = 1000000;
constexpr uint8_t  kBusReadChunk  = 2;
constexpr uint32_t kBusRespTimeoutUs = 3000;
constexpr uint32_t kBusInterFrameGapUs = 200;
constexpr uint8_t  kBusSteeringIds[6] = {1, 2, 3, 4};
constexpr uint8_t  kBusArmIds[4] = {5, 6, 7, 8};

// ---- バスlittle/big の判定は feetech::Endianness を使う ----
constexpr bool kBusLittleEndian = true;

// ---- ★未実装★ Phase 2 の計画値。実装には存在しない軸数 ----
// 実用の軸数（kNumSteeringServos など）とは別で管理する。
constexpr uint8_t kPlannedSteeringCount = 4;
constexpr uint8_t kPlannedArmBusCount   = 3;
constexpr uint8_t kPlannedGripperCount  = 2;

}  // namespace config
}  // namespace meister
