<?xml version="1.0"?>
<package format="3">
  <name>perception</name>
  <version>0.1.0</version>
  <description>Image recognition package for Meister autonomous robot</description>
  <maintainer email="s25089@tokyo.kosen-ac.jp">Team Ume Onigiri</maintainer>
  <license>Apache 2.0</license>
  
  <buildtool_depend>ament_python</buildtool_depend>
  
  <exec_depend>rclpy</exec_depend>
  <exec_depend>yolo_ros</exec_depend>
  <exec_depend>ultralytics</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>vision_msgs</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
