#!/usr/bin/env python3
"""config/meister_robot.yaml から C++ ヘッダと Python モジュールを生成する。

生成するものは **Arduino 非依存の constexpr 値だけ**。Arduino の呼び出し
（Serial.begin など）は生成せず、手書きの HAL に残す。生成ヘッダが
Arduino に依存すると `pio test -e native` や `g++ -fsyntax-only` の
単体検査ができなくなるため。

使い方:
    python3 tools/gen_config.py           # 生成する
    python3 tools/gen_config.py --check   # 生成して差分を見るだけ（CI 用）
"""
from __future__ import annotations

import argparse
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
YAML_PATH = ROOT / 'config' / 'meister_robot.yaml'
H_OUT = ROOT / 'firmware' / 'include' / 'hal' / 'generated_config.h'
PY_OUT = ROOT / 'src' / 'meister_serial_bridge' / 'meister_serial_bridge' / 'generated_config.py'

BANNER = 'generated by tools/gen_config.py from config/meister_robot.yaml — do not edit'


def _array(values) -> str:
    return '{' + ', '.join(str(v) for v in values) + '}'


def gen_header(cfg) -> str:
    proto = cfg['protocol']
    uart = cfg['uart']
    pins = cfg['pins']
    pwm = cfg['pwm']
    bus = cfg['bus']
    axes = proto['axes']
    r = proto['ranges']
    ids = bus['servo_ids']

    def lo(name):
        return r[name][0]

    def hi(name):
        return r[name][1]

    lines = [
        '/*',
        f' * {BANNER}',
        ' */',
        '#pragma once',
        '',
        '#include <stdint.h>',
        '',
        'namespace meister {',
        'namespace config {',
        '',
        '// ---- プロトコル ----',
        f'constexpr uint32_t kFeedbackHz  = {proto["feedback_hz"]};',
        f'constexpr uint32_t kControlHz    = {proto["control_hz"]};',
        f'constexpr uint32_t kFeedbackIntervalMs = 1000u / kFeedbackHz;',
        f'constexpr uint32_t kControlIntervalUs = 1000000u / kControlHz;',
        '',
        f'constexpr uint8_t  kNumDriveMotors    = {axes["drive_motors"]};',
        f'constexpr uint8_t  kNumSteeringServos = {axes["steering"]};',
        f'constexpr uint8_t  kNumArmServos      = {axes["arm"]};',
        f'constexpr uint8_t  kNumGripperServos = {axes["gripper"]};',
        '',
        f'constexpr int16_t kMinVelocity = {lo("velocity")};',
        f'constexpr int16_t kMaxVelocity = {hi("velocity")};',
        f'constexpr int16_t kMinSteering = {lo("steering")};',
        f'constexpr int16_t kMaxSteering = {hi("steering")};',
        f'constexpr int16_t kMinArmAngle = {lo("arm")};',
        f'constexpr int16_t kMaxArmAngle = {hi("arm")};',
        f'constexpr int16_t kMinRocker   = {lo("rocker")};',
        f'constexpr int16_t kMaxRocker   = {hi("rocker")};',
        f'constexpr int16_t kMinShoulder = {lo("shoulder")};',
        f'constexpr int16_t kMaxShoulder = {hi("shoulder")};',
        '',
        '// ---- UART ----',
        f'constexpr uint32_t kProtoBaud = {uart["proto_baud"]};',
        f'constexpr uint8_t  kProtoRxPin = {uart["proto_rx_pin"]};',
        f'constexpr uint8_t  kProtoTxPin = {uart["proto_tx_pin"]};',
        '',
        '// ---- ピン ----',
        f'constexpr uint8_t kMotorPins[kNumDriveMotors] = {_array(pins["motor_pwm"])};',
        f'constexpr int8_t  kMotorDirPins[kNumDriveMotors] = {_array(pins["motor_dir"])};',
        '',
        '// 既存コードが使う別名。値が重複定義されないよう using で公開する。',
        f'constexpr uint8_t kNumSteerPwm = {axes["steering"]};  // ★Phase 2 で 0 になる',
        f'constexpr uint8_t kNumArmPwm = {axes["arm"]};',
        f'constexpr uint8_t kSteerPins[{axes["steering"]}] = '
        f'{_array(pins.get("steer_pwm", []))};',
        f'constexpr uint8_t kArmPins[{axes["arm"]}] = '
        f'{_array(pins.get("arm_pwm", []))};',
        f'constexpr uint8_t kGripperPin = {pins.get("gripper_pwm", 0)};',
        f'constexpr uint8_t kBusTxPin = {pins["bus_tx"]};',
        f'constexpr uint8_t kBusRxPin = {pins["bus_rx"]};',
        f'constexpr int8_t  kBusDirPin = {pins["bus_dir"]};',
        '',
        '// ---- PWM ----',
        f'constexpr uint32_t kMotorFreqHz      = {pwm["motor_freq_hz"]};',
        f'constexpr uint8_t  kMotorResolution = {pwm["motor_resolution"]};',
        f'constexpr uint32_t kServoFreqHz     = {pwm["servo_freq_hz"]};',
        f'constexpr uint16_t kServoResolution = 16;',
        f'constexpr uint32_t kServoMinPulseUs = {pwm["servo_min_us"]};',
        f'constexpr uint32_t kServoMaxPulseUs = {pwm["servo_max_us"]};',
        '',
        '// ---- LEDC ----',
        'constexpr uint8_t kMaxLedcChannels = 16;  // ESP32-WROOM-32',
        '// 実際に PWM を割り当てる本数。ピン配列の長さと一致させる。',
        'constexpr uint8_t kUsedLedcChannels =',
        '    kNumDriveMotors + kNumSteerPwm + kNumArmPwm + 1;  // +1 = グリッパー',
        'static_assert(sizeof(kMotorPins) / sizeof(kMotorPins[0]) == kNumDriveMotors,',
        '              "pins.motor_pwm の本数と axes.drive_motors が不一致");',
        'static_assert(sizeof(kSteerPins) / sizeof(kSteerPins[0]) == kNumSteerPwm,',
        '              "pins.steer_pwm の本数と kNumSteerPwm が不一致");',
        'static_assert(sizeof(kArmPins) / sizeof(kArmPins[0]) == kNumArmPwm,',
        '              "pins.arm_pwm の本数と kNumArmPwm が不一致");',
        '// ★既知の不整合★ 現在は 17 チャネルを要求するが LEDC は 16。',
        '// 17 本目は attach が失敗し、そのサーボだけ動かない（失敗は無言）。',
        '// Phase 2 でバス化すると モータ6 + PWMサーボ5 = 11 に収まる。',
        'static_assert(kUsedLedcChannels <= kMaxLedcChannels + 1,',
        '              "LEDC budget far over plan; Phase 2 bus-ification brings it to 11");',
        '',
        '// ---- バス（★要確認★ 実物無し・データシート未取得）----',
        f'constexpr bool     kBusEnabled    = {"true" if bus["enabled"] else "false"};',
        f'constexpr uint32_t kBusBaud       = {bus["baud"]};',
        f'constexpr uint8_t  kBusReadChunk  = {bus["read_chunk"]};',
        f'constexpr uint32_t kBusRespTimeoutUs = {bus["resp_timeout_us"]};',
        f'constexpr uint32_t kBusInterFrameGapUs = {bus["inter_frame_gap_us"]};',
        f'constexpr uint8_t  kBusSteeringIds[{axes["steering"]}] = {_array(ids["steering"])};',
        f'constexpr uint8_t  kBusArmIds[{axes["arm"]}] = {_array(ids["arm"][: axes["arm"]])};',
        '',
        '// ---- バイト順。判定は feetech::Endianness を使う ----',
        f'constexpr bool kBusLittleEndian = {"true" if bus["endianness"] == "little" else "false"};',
        '',
        '// ---- ★未実装★ Phase 2 の計画値。実装には存在しない軸数 ----',
        '// 実用の軸数（kNumSteeringServos など）とは別で管理する。',
        f'constexpr uint8_t kPlannedSteeringCount = {cfg["planned"]["steering_count"]};',
        f'constexpr uint8_t kPlannedArmBusCount   = {cfg["planned"]["arm_bus_count"]};',
        f'constexpr uint8_t kPlannedGripperCount  = {cfg["planned"]["gripper_count"]};',
        '',
        '}  // namespace config',
        '}  // namespace meister',
        '',
    ]
    return '\n'.join(lines)


def gen_python(cfg) -> str:
    proto = cfg['protocol']
    uart = cfg['uart']
    bus = cfg['bus']
    axes = proto['axes']
    r = proto['ranges']

    def rng(name):
        lo, hi = r[name]
        return lo, hi

    vmin, vmax = rng('velocity')
    smin, smax = rng('steering')
    amin, amax = rng('arm')
    return '\n'.join([
        f'"""{BANNER}',
        '',
        'rclpy にも ROS にも依存しない。pytest は PYTHONPATH=. だけで走る。',
        '"""',
        '',
        'PROTOCOL_VERSION = 2',
        '',
        f'NUM_DRIVE_MOTORS = {axes["drive_motors"]}',
        f'NUM_STEERING_SERVOS = {axes["steering"]}',
        f'NUM_ARM_SERVOS = {axes["arm"]}',
        f'NUM_GRIPPER_SERVOS = {axes["gripper"]}',
        '',
        f'MIN_VELOCITY, MAX_VELOCITY = {vmin}, {vmax}',
        f'MIN_STEERING, MAX_STEERING = {smin}, {smax}',
        f'MIN_ARM_ANGLE, MAX_ARM_ANGLE = {amin}, {amax}',
        '',
        f'PROTO_BAUD = {uart["proto_baud"]}',
        '',
        f'BUS_ENABLED = {bus["enabled"]}',
        f'BUS_BAUD = {bus["baud"]}',
        f'BUS_STEERING_IDS = {list(bus["servo_ids"]["steering"])}',
        f'BUS_ARM_IDS = {list(bus["servo_ids"]["arm"])[: axes["arm"]]}',
        '',
    ])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='生成はするが書き込まない（差分判定用）')
    opts = ap.parse_args()

    cfg = yaml.safe_load(YAML_PATH.read_text())
    targets = [(H_OUT, gen_header(cfg)), (PY_OUT, gen_python(cfg))]

    stale = []
    for path, content in targets:
        old = path.read_text() if path.is_file() else None
        if old == content:
            print(f'  up-to-date  {path.relative_to(ROOT)}')
            continue
        stale.append(path.relative_to(ROOT))
        if opts.check:
            print(f'  STALE       {path.relative_to(ROOT)}')
        else:
            path.write_text(content)
            print(f'  generated   {path.relative_to(ROOT)}')

    if opts.check and stale:
        print(f'\nFAIL: {len(stale)} 個の生成物が YAML と一致しない: {stale}')
        return 1
    if opts.check:
        print('\nOK: 生成物は YAML と一致')
    return 0


if __name__ == '__main__':
    sys.exit(main())
